---
- name: Reload systemd services
  systemd:
    daemon_reload: true

- name: Install pretalx plugins
  shell: cd ~/plugins/{{ item.name }} && {{ pretalx_python }} setup.py develop --user
  with_items: "{{ pretalx_plugins }}"
  become: true
  become_user: "{{ pretalx_system_user }}"

- name: Compile messages for plugins
  shell: cd {{ pretalx_system_home }}/plugins/{{ item.name }} && make
  with_items: "{{ pretalx_plugins }}"
  become: true
  become_user: "{{ pretalx_system_user }}"

- name: Run pretalx migrations
  command: "{{ pretalx_python }} -m pretalx migrate"
  become: true
  become_user: "{{ pretalx_system_user }}"

- name: Compile pretalx messages
  command: "{{ pretalx_python }} -m pretalx compilemessages"
  become: true
  become_user: "{{ pretalx_system_user }}"

- name: Compile pretalx styles
  command: "{{ pretalx_python }} -m pretalx regenerate_css"
  become: true
  become_user: "{{ pretalx_system_user }}"

- name: Compile pretalx javascript
  command: "{{ pretalx_python }} -m pretalx rebuild --npm-install"
  become: true
  become_user: "{{ pretalx_system_user }}"

- name: Collect static pretalx files
  command: "{{ pretalx_python }} -m pretalx collectstatic --noinput"
  become: true
  become_user: "{{ pretalx_system_user }}"

- name: Compress static pretalx files
  command: "{{ pretalx_python }} -m pretalx compress"
  become: true
  become_user: "{{ pretalx_system_user }}"

- name: Restart pretalx service
  service:
    name: pretalx@{{ pretalx_instance_identifier }}
    state: restarted

- name: Restart worker service
  service:
    name: pretalx-worker@{{ pretalx_instance_identifier }}
    state: restarted
  when: pretalx_celery

- name: Restart redis
  service:
    name: redis
    state: restarted
  when: pretalx_redis

- name: Reload nginx
  service:
    name: nginx
    state: reloaded

- name: Restart pretalx socket
  service:
    name: pretalx@{{ pretalx_instance_identifier }}.socket
    state: restarted


